[core] fix loading embedded module so
LSPosed/LSPosed pull request #1036
Opened 2021-09-02 10:50 UTC by Dr-TSNG

2021-09-02 13:37 UTC, yujincheng08 requested changes
Extract loop invariants

2021-09-03 02:35 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedInit.java
> +                    sb.append(file.hostApk.substring(0, file.hostApk.lastIndexOf('/'))).append("/lib/").append(arch).append("/").append(name).append(".so!/lib/").append(abi).append(File.pathSeparator
file.hostApk.substring(0, file.hostApk.lastIndexOf('/') can be extracted too

2021-09-03 08:57 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedInit.java
> +                var hostDir = file.hostApk.substring(0, file.hostApk.lastIndexOf('/'));
File.getParent?

2021-09-03 09:34 UTC, Dr-TSNG commented on core/src/main/java/de/robv/android/xposed/XposedInit.java
> +                var hostDir = file.hostApk.substring(0, file.hostApk.lastIndexOf('/'));
是个 String，不是 File

2021-09-03 09:36 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedInit.java
> +                var hostDir = file.hostApk.substring(0, file.hostApk.lastIndexOf('/'));
你可以 new File

2021-09-03 09:48 UTC, Dr-TSNG commented on core/src/main/java/de/robv/android/xposed/XposedInit.java
> +                var hostDir = file.hostApk.substring(0, file.hostApk.lastIndexOf('/'));
有必要整这么麻烦嘛？这开销没啥区别吧

2021-09-03 11:12 UTC, yujincheng08 approved these changes

2021-09-03 11:16 UTC, merged