Patch 1
LSPosed/LSPosed pull request #1202
Opened 2021-10-01 02:47 UTC by Howard20181

2021-10-01 02:50 UTC, yujincheng08 commented
治标不治本，为什么 old == null

2021-10-01 03:11 UTC, Howard20181 commented
> 治标不治本，为什么 old == null

因为installedModules里面没有这个模块
奇怪的是
这是在卸载时发生的
不应该早就在里面了吗

2021-10-01 03:12 UTC, yujincheng08 commented
那就是在其他地方删掉了，你得找到那个地方

2021-10-01 03:29 UTC, Howard20181 commented
Xposed模块卸载时isXposedModule=false
这个有没有影响？

2021-10-01 03:29 UTC, yujincheng08 commented
> Xposed模块卸载时isXposedModule=false 这个有没有影响？

有

2021-10-02 14:16 UTC, yujincheng08 requested changes

2021-10-02 14:16 UTC, yujincheng08 commented on core/src/main/java/org/lsposed/lspd/service/LSPosedService.java
> -                applicationInfo = PackageService.getApplicationInfo(moduleName, PackageManager.GET_META_DATA | PackageService.MATCH_ALL_FLAGS, 0);
meaningless

2021-10-03 00:45 UTC, Howard20181 commented
安装模块后不启用直接卸载会不发送广播，因为数据库中没有这个模块
要不要安装模块时就更新apk路径？
可以直接在另一个PR改

2021-10-03 02:43 UTC, yujincheng08 approved these changes

2021-10-03 02:43 UTC, merged