[core] Update the apk path when installing the module for the first time
LSPosed/LSPosed pull request #1221
Opened 2021-10-03 17:58 UTC by Howard20181

2021-10-03 19:11 UTC, yujincheng08 requested changes

2021-10-03 19:11 UTC, yujincheng08 commented on core/src/main/java/org/lsposed/lspd/service/LSPosedService.java
> +                    configManager.updateModuleApkPath(moduleName,configManager.getModuleApkPath(applicationInfo), false);
format

2021-10-03 21:36 UTC, Howard20181 commented
现在已经在卸载后尽快广播给管理器了
还有一种情况需要管理器规避
当用户安装一个模块并卸载它后然后从通知点进来
在ScopeAdapter的refresh()里面判断一下如果没有这个模块就直接退出
怎么说都是防手贱

2021-10-04 11:45 UTC, yujincheng08 approved these changes

2021-10-04 11:45 UTC, merged