[app] Optimize module list loading
LSPosed/LSPosed pull request #1401
Opened 2021-11-13 05:59 UTC by Howard20181

2021-11-13 18:11 UTC, yujincheng08 requested changes

2021-11-13 18:11 UTC, yujincheng08 commented on app/src/main/java/org/lsposed/manager/ui/fragment/ModulesFragment.java
> +            var snapshot = adapters.get(position).snapshot().parallelStream().map(m -> m.packageName).collect(Collectors.toSet());
m.packageName 不是耗时操作无需 parallel

2021-11-13 18:11 UTC, yujincheng08 commented on app/src/main/java/org/lsposed/manager/ui/fragment/ModulesFragment.java
> +                        .filter(module -> user == null ? module.userId == 0 : module.userId == user.id)
这也不是最耗时的操作，后面的更耗时，应该把后面的也弄进来

2021-11-13 18:11 UTC, yujincheng08 requested changes

2021-11-13 18:11 UTC, yujincheng08 commented on app/src/main/java/org/lsposed/manager/ui/fragment/HomeFragment.java
> +                Looper.myQueue().addIdleHandler(() -> {
全部改用线程池算了

2021-11-13 18:25 UTC, Howard20181 commented on app/src/main/java/org/lsposed/manager/ui/fragment/HomeFragment.java
> +                Looper.myQueue().addIdleHandler(() -> {
会导致每次从其他页面返回到主页都显示加载中
仅第一次用是为了提升启动速度

2021-11-13 18:40 UTC, yujincheng08 commented on app/src/main/java/org/lsposed/manager/ui/fragment/HomeFragment.java
> +                Looper.myQueue().addIdleHandler(() -> {
那就不要放这里加载，放 onCreate 这些地方就不会多次加载

2021-11-13 18:41 UTC, yujincheng08 commented on app/src/main/java/org/lsposed/manager/ui/fragment/HomeFragment.java
> +                Looper.myQueue().addIdleHandler(() -> {
而且明明有个 `ModuleListener` 你设置个回调不就好

2021-11-13 18:56 UTC, yujincheng08 commented on app/src/main/java/org/lsposed/manager/ui/fragment/ModulesFragment.java
> -                binding.tabLayout.setTabGravity(TabLayout.GRAVITY_FILL);
这些怎么没了

2021-11-15 17:08 UTC, Howard20181 commented on app/src/main/java/org/lsposed/manager/ui/fragment/AppListFragment.java
> +        scopeAdapter.refresh();
这是为什么？

2021-11-20 16:46 UTC, yujincheng08 approved these changes

2021-11-20 16:47 UTC, merged