[Milestone] Framework in C/S model via binder
LSPosed/LSPosed pull request #155
Opened 2021-02-20 11:46 UTC by yujincheng08

Description to be completed.

2021-02-20 12:00 UTC, aviraxp commented on core/src/main/java/io/github/lsposed/lspd/service/ConfigManager.java
> +    private final static SQLiteStatement createModulesTable = db.compileStatement("CREATE TABLE IF NOT EXISTS modules (" +
嘿嘿嘿

2021-02-20 12:05 UTC, aviraxp commented on app/src/main/java/io/github/lsposed/manager/ui/activity/LogsActivity.java
> +                            if (parcelFileDescriptor == null) {
close os before return？

2021-02-21 07:11 UTC, RikkaW requested changes

2021-02-21 07:11 UTC, RikkaW commented on core/src/main/java/io/github/lsposed/lspd/service/ActivityManagerService.java
> +        return am;
The binder is cached forever, once the system server restarts, the root service can never get the new binder.

The correct implementation from Sui:
https://github.com/RikkaApps/Sui/blob/master/module/src/main/java/rikka/sui/server/api/SystemServiceBinder.kt

2021-02-22 10:25 UTC, tehcneko submitted a review, later dismissed

2021-02-22 10:46 UTC, tehcneko approved these changes

2021-02-22 10:46 UTC, merged