Fix performance traps of reflection members in `XposedHelpers.java`
LSPosed/LSPosed pull request #1719
Opened 2022-02-23 12:43 UTC by RinOrz

### Reason
Recalculating and generating a string as a key of a cache map for each call is actually 10x slower than object references, so that's are performance traps.

### Benchmark
https://github.com/meowool-catnip/cloak/blob/0b26ee46d61a731b882d6617a05a2f3be3c3ad61/api/src/benchmark/kotlin/com/meowool/cloak/ReflectionObjectAccessTests.kt#L37-L65

even in different systems, their performance is also
https://github.com/meowool-catnip/cloak/actions/runs/1886844225

2022-02-23 12:47 UTC, RinOrz commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +    private static final ConcurrentHashMap<MemberCacheKey.Constructor, Constructor<?>> constructorCache = new ConcurrentHashMap<>();
这里保证了线程安全，并且也许会对性能有所提升，因此修改了

2022-02-23 20:08 UTC, yujincheng08 requested changes

2022-02-23 20:08 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +     * @see <a href="https://github.com/meowool-catnip/cloak/blob/main/api/src/benchmark/kotlin/com/meowool/cloak/ReflectionObjectAccessTests.kt#L37-L65https://github.com/meowool-catnip/cloak/blob/ma
网址重复了。

2022-02-23 20:09 UTC, yujincheng08 requested changes

2022-02-23 20:09 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +        if (fieldCache.containsKey(fieldKey)) {
不是原子操作，应该是 ComputeIfAbsent

2022-02-23 20:11 UTC, yujincheng08 requested changes

2022-02-23 20:11 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +            private final Class<?> clazz;
直接存 class 就不能 GC 了吧？或许应该 weak reference？

2022-02-23 20:11 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +            private final Class<?>[] parameters;
同理，GC

2022-02-23 20:23 UTC, yujincheng08 commented
另外我不是很理解为什么 Class.getName 会慢。Class 内部不是会缓存自己名字吗？

2022-02-23 20:24 UTC, yujincheng08 commented
而且我觉得你可以让 key 缓存自己的 hashCode，这样更快

2022-02-23 20:39 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                if (o == null || getClass() != o.getClass()) return false;
```suggestion
                if (!(o instanceof Constructor)) return false;
```

2022-02-23 20:40 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +
```suggestion
        private final int hash;
        private final String name;

        protected MemberCacheKey(int hash, String name) {
            this.hash = hash;
            this.name = name;
        }

        @Override
        public abstract boolean equals(@Nullable Object obj);

        @Override
        final public int hashCode() {
            return hash;
        }

        @NonNull
        @Override
        final public String toString() {
            return name;
        }

```

2022-02-24 03:43 UTC, RinOrz commented
> 另外我不是很理解为什么 Class.getName 会慢。Class 内部不是会缓存自己名字吗？

我认为慢的原因可能是来自于字符串创建本身
`class.name + getParameters(..) + ...`

2022-02-24 03:44 UTC, yujincheng08 commented
建议在 ART 上来一次 benchmark

2022-02-24 04:39 UTC, RinOrz commented
android上的benchmark我还没尝试过，我需要研究研究😶，到时候再创建一个新pr? 考虑加个benchmark module/sources set到这个仓库

2022-02-24 07:11 UTC, vvb2060 commented
我在Android上跑了测试，2后缀使用此PR的XposedHelpers 
<details>

```
{
    "context": {
        "build": {
            "brand": "google",
            "device": "walleye",
            "fingerprint": "google/walleye/walleye:11/RP1A.201005.004.A1/6934943:user/release-keys",
            "model": "Pixel 2",
            "version": {
                "sdk": 30
            }
        },
        "cpuCoreCount": 8,
        "cpuLocked": true,
        "cpuMaxFreqHz": 2457600000,
        "memTotalBytes": 3834609664,
        "sustainedPerformanceModeEnabled": false
    },
    "benchmarks": [
        {
            "name": "findField2",
            "params": {},
            "className": "io.github.vvb2060.benchmark.ExampleBenchmarkTest",
            "totalRunTimeNs": 5442780177,
            "metrics": {
                "timeNs": {
                    "minimum": 1938.9050822974873,
                    "maximum": 2207.9636978750905,
                    "median": 2082.231782415327,
                    "runs": [
                        2127.9054244117533,
                        2156.4664157828715,
                        1997.1199300566389,
                        2015.2432812559396,
                        2067.3682289884823,
                        2089.5858516744593,
                        2070.7754970160036,
                        2053.410423081309,
                        2057.2492872619455,
                        2054.7052115406545,
                        2093.058463526818,
                        2102.9299045881326,
                        2096.16086973049,
                        2110.134450906603,
                        2073.0166875736495,
                        2082.2565476869277,
                        1966.3217394609799,
                        2164.22537727601,
                        2059.3697114836355,
                        2106.0223894780856,
                        2040.2861215646026,
                        2001.9210476299083,
                        2207.9636978750905,
                        2095.8896111301174,
                        2136.891853879196,
                        2050.5515642224505,
                        2044.5506899304369,
                        1960.944501463489,
                        1938.9050822974873,
                        2140.2298247614704,
                        2062.034553540883,
                        2130.7444786558713,
                        2029.1951571824989,
                        2033.5547192762383,
                        2132.718363933554,
                        2139.7210248222905,
                        2121.9401680161172,
                        2100.504618542593,
                        2095.85399323374,
                        2107.4656555289466,
                        1953.308320979207,
                        2117.4994108032083,
                        2020.0978446801232,
                        2109.4355874862204,
                        1945.672102482229,
                        2060.7238757745085,
                        2120.7503326110923,
                        2046.6473182042803,
                        2184.916562131752,
                        2082.207017143726
                    ]
                },
                "allocationCount": {
                    "minimum": 21.0,
                    "maximum": 21.000342114266164,
                    "median": 21.000152050784962,
                    "runs": [
                        21.00003801269624,
                        21.000152050784962,
                        21.0,
                        21.000152050784962,
                        21.000342114266164
                    ]
                }
            },
            "sampledMetrics": {},
            "warmupIterations": 973421,
            "repeatIterations": 26307,
            "thermalThrottleSleepSeconds": 0
        },
        {
            "name": "findField",
            "params": {},
            "className": "io.github.vvb2060.benchmark.ExampleBenchmarkTest",
            "totalRunTimeNs": 6340322767,
            "metrics": {
                "timeNs": {
                    "minimum": 6569.669466882068,
                    "maximum": 7395.547980613894,
                    "median": 6971.985040387723,
                    "runs": [
                        7104.69576736672,
                        7177.3196768982225,
                        6989.163295638126,
                        7095.793667205169,
                        6777.10423263328,
                        6922.301453957997,
                        6856.230500807755,
                        6569.669466882068,
                        6571.264814216478,
                        6776.1247819063,
                        6812.1472697899835,
                        6659.656672051697,
                        6942.098158319871,
                        6901.848400646203,
                        6969.501195476575,
                        7283.966785137318,
                        7383.69421647819,
                        6869.00310177706,
                        7395.547980613894,
                        7328.1509531502425,
                        7050.41802907916,
                        7088.08633279483,
                        7166.923166397415,
                        7117.949660743134,
                        6853.706235864297,
                        7035.090920840064,
                        6742.751082390953,
                        6863.426235864297,
                        7063.1435864297255,
                        6974.468885298869,
                        6912.7598061389335,
                        7254.14042003231,
                        6924.53957996769,
                        6915.5701453958,
                        7109.54901453958,
                        6872.180290791599,
                        7216.815444264944,
                        7146.046074313409,
                        6976.441227786753,
                        6705.87366720517,
                        7303.019709208401,
                        7066.987140549273,
                        6988.708949919224,
                        6837.655508885299,
                        7094.487819063005,
                        6929.238061389337,
                        6821.37253634895,
                        6620.302229402262,
                        7061.5010662358645,
                        6867.801615508885
                    ]
                },
                "allocationCount": {
                    "minimum": 35.00045234248788,
                    "maximum": 35.001098546042,
                    "median": 35.00071082390953,
                    "runs": [
                        35.001098546042,
                        35.000775444264946,
                        35.00058158319871,
                        35.00045234248788,
                        35.00071082390953
                    ]
                }
            },
            "sampledMetrics": {},
            "warmupIterations": 41104,
            "repeatIterations": 15475,
            "thermalThrottleSleepSeconds": 0
        },
        {
            "name": "findMethodExact",
            "params": {},
            "className": "io.github.vvb2060.benchmark.ExampleBenchmarkTest",
            "totalRunTimeNs": 6426557984,
            "metrics": {
                "timeNs": {
                    "minimum": 8384.225507391631,
                    "maximum": 9718.534285475653,
                    "median": 9207.171051532616,
                    "runs": [
                        9055.127536958156,
                        9310.750522007851,
                        9445.324145995155,
                        8384.225507391631,
                        8591.393134552744,
                        9342.027394972021,
                        9078.008853253154,
                        9439.294913555499,
                        9348.043598095715,
                        9314.143573039339,
                        9225.650129457947,
     [...]

2022-02-24 07:14 UTC, vvb2060 commented
我认为还需要测试使用new StringBuilder(int capacity)替换直接拼接字符串

2022-02-24 08:21 UTC, RinOrz commented on benchmark/src/androidTest/java/org/lsposed/lspd/cases/StringBuilderXposedHelpers.java
> +
> 我认为还需要测试使用new StringBuilder(int capacity)替换直接拼接字符串

已测试

2022-02-24 08:23 UTC, RinOrz commented
这是我在 android 设备上的测试结果：
![image](https://user-images.githubusercontent.com/58068445/155485903-e8275979-7507-4154-b6ae-cbabf9a50dd6.png)

### JSON 
https://github.com/RinOrz/LSPosed/blob/master/benchmark/src/result/ReflectionCacheBenchmark.json

2022-02-24 09:21 UTC, RinOrz commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +            private final Class<?> clazz;
感谢指出，是我的知识盲区了！
不过我去学习并尝试了一下，发现即使使用 `WeakReference` 它也不会被 GC?
https://github.com/RinOrz/LSPosed/blob/b9eacd4f6a96a041a14ac36f013d084744f0f004/benchmark/src/androidTest/java/org/lsposed/lspd/HashMapGCTest.kt

2022-02-24 17:24 UTC, yujincheng08 commented
benchmark 可以不用加上来吧

2022-02-24 17:46 UTC, RinOrz commented
好，那么只剩下GC那个问题了

2022-02-24 17:49 UTC, yujincheng08 requested changes

2022-02-24 17:49 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                        throw new NoSuchMethodError(key.toString());
这个 throw 不会传出来吧

2022-02-24 17:49 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                if (o == null || getClass() != o.getClass()) return false;
还没改进

2022-02-24 17:49 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +
还没改进

2022-02-24 17:51 UTC, yujincheng08 commented
weakreference 的内容确实可以被 gc 的，这个没问题。

2022-02-24 17:54 UTC, RinOrz commented
剩下的修改还没push，是打算将GC那个解决完再一起的

> weakreference 的内容确实可以被 gc 的，这个没问题。

好，那我明天将 key 内部持有都改为 weakref？

2022-02-24 17:55 UTC, yujincheng08 commented
map 的结果也要，因为结果的 gc root 也是 class

2022-02-24 18:01 UTC, RinOrz commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                        throw new NoSuchMethodError(key.toString());
会的 https://pl.kotl.in/a6fuOzG1n

2022-02-24 18:07 UTC, RinOrz commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                        throw new NoSuchMethodError(key.toString());
但是这里好像有一个小问题，`getDeclaredMethod` 本身就会 throw NoSuchMethodException，既然如此，那么我感觉没必要再catch了？这里我被 XposedHelpers 之前的代码影响了

2022-02-24 19:03 UTC, yujincheng08 commented
想了一下还是不考虑 GC 了😂因为考虑了 GC 那 cache 的命中率就低了，也有悖 cache 的意图了。

2022-02-24 19:11 UTC, yujincheng08 requested changes

2022-02-24 19:11 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                        throw new NoSuchMethodError(key.toString());
但是抛出异常之后 map 不会更新值，也就是方法不存在的情况没有被 cache 了。

2022-02-24 19:11 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                        throw new NoSuchMethodError(key.toString());
另外 ConcurrentHashMap 不支持 null value，需要 Optional 封装

2022-02-24 20:48 UTC, RinOrz commented
> 想了一下还是不考虑 GC 了😂因为考虑了 GC 那 cache 的命中率就低了，也有悖 cache 的意图了。

Okk，其实如果实在需要保证内存的严谨性的话也许可以引用 https://github.com/ben-manes/caffeine ? 不过就一个场景好像也没什么必要

那 key 的那处我就暂时不做修改了

2022-02-24 20:49 UTC, yujincheng08 commented
hashcode 缓存还是可以做的

2022-02-24 21:26 UTC, RinOrz commented
memberKey 的 hashcode 缓存的话雀食感觉不会有什么问题，那个我本地已经按照建议加上了，明天我再推送一次吧，再看看有什么问题（顺便说一句，足够严谨！

2022-02-25 07:36 UTC, yujincheng08 requested changes

2022-02-25 07:36 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +            private static int hashCode(Class<?> clazz, Class<?>[] parameters, boolean isExact) {
为什么不用缓存的

2022-02-25 07:36 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +        public int hashCode() {
final 掉

2022-02-25 07:37 UTC, yujincheng08 commented on settings.gradle.kts
>      ":hiddenapi-bridge",
这个文件不用改

2022-02-25 07:38 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +            private static int hashCode(Class<?> clazz, Class<?>[] parameters, boolean isExact) {
哦这个是 static 的

2022-02-25 07:39 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +            private static int hashCode(Class<?> clazz, Class<?>[] parameters, boolean isExact) {
直接在构造函数算好了

2022-02-25 07:39 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                super(hashCode(clazz, parameters, isExact));
```suggestion
                super(31 * Objects.hash(clazz, isExact) + Arrays.hashCode(parameters));
```

2022-02-25 07:40 UTC, yujincheng08 commented on core/src/main/java/de/robv/android/xposed/XposedHelpers.java
> +                super(hashCode(clazz, name, parameters, isExact));
```suggestion
                super(31 * Objects.hash(clazz, name, isExact)+ Arrays.hashCode(parameters));
```

2022-02-25 07:56 UTC, yujincheng08 approved these changes

2022-02-25 08:01 UTC, merged

2022-02-25 09:08 UTC, yujincheng08 commented
有用户报告死锁了

2022-02-25 09:14 UTC, RinOrz commented
> 有用户报告死锁了

😢 怎么重现问题，我去研究一下

2022-02-25 09:14 UTC, yujincheng08 commented
看 tg 群吧