Separate core into bridge and loader
LSPosed/LSPosed pull request #1766
Opened 2022-03-16 14:20 UTC by Dr-TSNG

2022-03-16 15:37 UTC, yujincheng08 requested changes

2022-03-16 15:37 UTC, yujincheng08 commented on bridge/build.gradle.kts
> +    compileSdk = androidCompileSdkVersion
已经没有必要了

2022-03-16 16:49 UTC, Dr-TSNG commented on loader/src/main/jni/src/magisk_loader.cpp
> -        RegisterResourcesHook(env);
移到 bridge/context.cpp 里了

2022-03-16 16:53 UTC, yujincheng08 commented on loader/src/main/java/org/lsposed/lspd/core/Main.java
> +        Startup.bootstrapXposed(true, appDataDir, "system_server");
重复传参看着很别扭

2022-03-16 16:55 UTC, yujincheng08 requested changes

2022-03-16 16:55 UTC, yujincheng08 commented on bridge/build.gradle.kts
>  }
可删

2022-03-16 16:56 UTC, Dr-TSNG commented on manager-service/build.gradle.kts
>      id("com.android.library")
What(

2022-03-16 17:03 UTC, yujincheng08 requested changes

2022-03-16 17:03 UTC, yujincheng08 commented on bridge/build.gradle.kts
> +    compileOnly(project(":hiddenapi:stubs"))
用 projects.hiddenapi.stubs

2022-03-16 17:36 UTC, yujincheng08 requested changes

2022-03-17 05:37 UTC, yujincheng08 requested changes

2022-03-17 05:37 UTC, yujincheng08 commented on core/src/main/java/org/lsposed/lspd/core/Startup.java
> +    public static void bootstrapXposed(boolean isSystem, String niceName) {
直接用 `XposedInit.startsSystemServer` 就能删掉 `isSystem`

2022-03-17 11:12 UTC, yujincheng08 approved these changes

2022-03-17 11:12 UTC, merged