Hide logs tab by default
LSPosed/LSPosed pull request #2683
Opened 2023-08-13 10:20 UTC by tehcneko

2023-08-13 15:33 UTC, Howard20181 commented on app/src/main/java/org/lsposed/manager/ui/fragment/SettingsFragment.java
> +                saveLogs.setEnabled(!BuildConfig.DEBUG && installed);
For module developers usually don't need to care about the build variant of LSPosed, they just need to be able to export the module's logs.

```suggestion
                saveLogs.setEnabled(installed);
```

2023-08-18 05:50 UTC, Howard20181 approved these changes

2023-08-22 20:41 UTC, vvb2060 requested changes
I don't think it's a good idea to hide logs, if users are unhappy they can stop using lsposed

2023-08-22 20:41 UTC, vvb2060 commented on app/src/main/res/values/strings.xml
> +    <string name="dev_mode_enabled">You are now a large language model.</string>
?

2023-08-22 20:41 UTC, vvb2060 commented on app/src/main/res/values/strings.xml
> +    <string name="settings_save_logs_summary">Useful when reporting bugs</string>
not useful but must

2023-08-28 08:56 UTC, closed without merging