[core] Support riru24
LSPosed/LSPosed pull request #329
Opened 2021-03-10 20:04 UTC by yujincheng08

2021-03-10 20:07 UTC, kotori2 approved these changes

2021-03-11 00:20 UTC, tehcneko requested changes
就不能 zip 里就塞进 /riru 吗

2021-03-11 00:34 UTC, xiaocenter commented
> 就不能 zip 里就塞进 /riru 吗

riru 24还没发布吧？ 有了这个是不是不需要RIRU 面具模块了 ？

2021-03-11 10:55 UTC, tehcneko approved these changes

2021-03-11 10:57 UTC, merged