[core] Build libc++ ourselves
LSPosed/LSPosed pull request #406
Opened 2021-03-25 11:25 UTC by yujincheng08

2021-03-25 23:21 UTC, tehcneko requested changes

2021-03-25 23:21 UTC, tehcneko commented on .github/workflows/manager.yml
> +          key: gradle-manager-${{ github.sha }}
？

2021-03-26 03:19 UTC, yujincheng08 commented on .github/workflows/manager.yml
> +          key: gradle-manager-${{ github.sha }}
不改 build cache 就不会上传，导致 cache 命中率越来越低

2021-03-26 07:01 UTC, tehcneko approved these changes

2021-03-26 07:11 UTC, merged