Added Japanese Translation
LSPosed/LSPosed pull request #807
Opened 2021-07-07 13:42 UTC by yoshi818

Hello I'd made Japanese translation for your LSPosed.
If you like it, please pull this.

2021-07-07 13:46 UTC, yujincheng08 requested changes

2021-07-07 13:46 UTC, yujincheng08 commented on app/src/main/res/values-ja/strings.xml
> +    <string name="translators"><![CDATA[<a href="https://github.com/LSPosed/LSPosed">LSPosed</a>]]></string>
ここに名前を入れてください。

2021-07-07 13:48 UTC, yujincheng08 commented on app/src/main/res/values-ja/strings.xml
> +    <string name="translators"><![CDATA[<a href="https://github.com/LSPosed/LSPosed">LSPosed</a>]]></string>
ホームページと一緒に

2021-07-07 13:53 UTC, yujincheng08 commented on app/src/main/res/values-ja/strings.xml
> +    <string name="app_launch">Launch it</string>
起動します？

2021-07-07 13:55 UTC, yujincheng08 commented on app/src/main/res/values-ja/strings.xml
> +    <string name="use_recommended_message">Select recommended apps?</string>
未翻訳

2021-07-07 13:56 UTC, yujincheng08 commented on app/src/main/res/values-ja/strings.xml
> +    <string name="menu_hide">隠す…</string>
排除？

2021-07-07 14:14 UTC, yoshi818 commented
yujincheng08
Thank you for your reply.I've fixed your suggestion.

2021-07-07 14:14 UTC, yujincheng08 approved these changes

2021-07-07 14:14 UTC, merged

2021-07-07 14:15 UTC, yujincheng08 commented
thx so much. merged

2021-09-08 15:11 UTC, yujincheng08 commented
Hi contributor, we are here inviting you to use the localization manage platform Crowdin for translations. Please check: https://lsposed.crowdin.com/lsposed